services:
  - type: web
    name: ispa-forms
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: WHATSAPP_PHONE
        value: 15559707710
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GOOGLE_APPS_SCRIPT_URL
        value: "https://script.google.com/macros/s/AKfycby3Yamn9lnIVOi10ETnbivhP-JOEQmMzflAnnJJOI_CyFNp5RN8xxVqn9kQn3y6GH4S/exec"
